"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import SystemLoading from "@/components/system-loading";
import SiteHeader from "@/components/site-header";

type Assessment = { summary: string; suggestions: string[]; spokenText: string; model: string; createdAt: string };
type Detail = { session: { id: string; patientId: string; patientName: string; status: string; startedAt: string; completedAt: string | null; cancelledAt: string | null }; measurement: { heartRate: number; spo2: number; systolicBp: number; diastolicBp: number; hemoglobin: number; measuredAt: string; averageIr: number; signalQuality: string; sampleWindowCount: number; validWindowCount: number; heartRateMin: number; heartRateMax: number; spo2Min: number; spo2Max: number } | null; assessment: Assessment | null };
export default function SessionPage() {
  const { id } = useParams<{ id: string }>(); const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(""); const [assessing, setAssessing] = useState(false); const [speaking, setSpeaking] = useState(false); const startedAssessment = useRef(false); const startedSpeech = useRef(false);
  useEffect(() => { fetch(`/api/screening-sessions/${id}`).then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error); setDetail(data); }).catch((e) => setError(e.message)); }, [id]);
  useEffect(() => {
    if (!detail?.measurement || detail.assessment || startedAssessment.current) return;
    startedAssessment.current = true;
    void assess();
  }, [detail?.assessment, detail?.measurement]);
  useEffect(() => {
    if (!detail?.assessment || startedSpeech.current) return;
    startedSpeech.current = true;
    void speak();
  }, [detail?.assessment]);
  if (!detail) return <main className="min-h-screen bg-[#08090c] text-white">{error ? <p className="grid min-h-screen place-items-center text-red-300">{error}</p> : <SystemLoading label="Assembling screening report" />}</main>;
  const { session, measurement } = detail;
  async function assess() { setAssessing(true); setError(""); try { const response = await fetch(`/api/screening-sessions/${id}/assessment`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDetail((current) => current ? { ...current, assessment: data.assessment as Assessment } : current); } catch (e) { setError(e instanceof Error ? e.message : "Could not create assessment."); } finally { setAssessing(false); } }
  async function speak() { setSpeaking(true); setError(""); try { const response = await fetch(`/api/screening-sessions/${id}/assessment/speech`, { method: "POST" }); if (!response.ok) { const data = await response.json(); throw new Error(data.error); } const url = URL.createObjectURL(await response.blob()); const audio = new Audio(url); audio.onended = () => { URL.revokeObjectURL(url); setSpeaking(false); }; audio.onerror = () => { URL.revokeObjectURL(url); setSpeaking(false); setError("Could not play assessment audio."); }; await audio.play(); } catch (e) { const text = detail?.assessment?.spokenText; if (text && "speechSynthesis" in window) { const utterance = new SpeechSynthesisUtterance(text); utterance.onend = () => setSpeaking(false); utterance.onerror = () => { setSpeaking(false); setError(e instanceof Error ? `${e.message} Local audio also failed.` : "Could not create audio."); }; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); setError("Groq audio unavailable. Playing local device voice."); return; } setSpeaking(false); setError(e instanceof Error ? e.message : "Could not create audio."); } }
  return <main className="min-h-screen bg-[#08090c] text-white print:bg-white print:text-black"><SiteHeader /><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 print:max-w-none print:p-0"><nav className="flex justify-between print:hidden"><Link href={`/records/${session.patientId}`} className="text-sm text-white/55">← Patient profile</Link><button onClick={() => window.print()} className="future-button">Print / Save PDF</button></nav>
    <header className="mt-8 border-b border-white/10 pb-7 print:mt-0 print:border-gray-300"><p className="signal-label print:text-red-700">HemoSync screening report</p><h1 className="mt-3 text-4xl font-semibold">{session.patientName}</h1><p className="mt-2 text-sm text-white/40 print:text-gray-600">Session {session.id}</p></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Card label="Status" value={session.status}/><Card label="Started" value={new Date(session.startedAt).toLocaleString()}/><Card label="Finished" value={session.completedAt ? new Date(session.completedAt).toLocaleString() : session.cancelledAt ? new Date(session.cancelledAt).toLocaleString() : "In progress"}/></section>{measurement && <section className="mt-6 grid gap-4 sm:grid-cols-2"><Vital label="Estimated blood pressure" value={`${measurement.systolicBp}/${measurement.diastolicBp} mmHg`} range="Demo estimate only"/><Vital label="Estimated hemoglobin" value={`${measurement.hemoglobin} g/dL`} range="Demo estimate only"/></section>}
    {measurement ? <><section className="mt-6 grid gap-4 sm:grid-cols-2"><Vital label="Heart rate" value={`${measurement.heartRate} BPM`} range={`${measurement.heartRateMin ?? measurement.heartRate}–${measurement.heartRateMax ?? measurement.heartRate} BPM`}/><Vital label="Blood oxygen" value={`${measurement.spo2}%`} range={`${measurement.spo2Min ?? measurement.spo2}–${measurement.spo2Max ?? measurement.spo2}%`}/></section><section className="future-panel mt-6 grid gap-5 p-6 sm:grid-cols-4 print:border-gray-300 print:bg-white print:shadow-none"><Card label="Signal quality" value={measurement.signalQuality ?? "Unknown"}/><Card label="Valid windows" value={`${measurement.validWindowCount ?? 1} / ${measurement.sampleWindowCount ?? 1}`}/><Card label="Average IR" value={String(measurement.averageIr ?? 0)}/><Card label="Measured" value={new Date(measurement.measuredAt).toLocaleString()}/></section><section className="future-panel mt-6 p-6 print:border-gray-300 print:bg-white print:shadow-none"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="signal-label print:text-red-700">AI screening guidance</p><h2 className="mt-2 text-2xl font-semibold">Patient note and suggestions</h2></div>{detail.assessment ? <button onClick={speak} disabled={speaking} className="rounded-xl border border-white/10 px-5 py-3 text-sm print:hidden">{speaking ? "Playing…" : "▶ Play assessment"}</button> : <button onClick={assess} disabled={assessing} className="future-button print:hidden">{assessing ? "Assessing…" : "Create assessment"}</button>}</div>{detail.assessment && <div className="mt-5 border-t border-white/10 pt-5"><p className="max-w-3xl leading-7 text-white/75 print:text-gray-700">{detail.assessment.summary}</p><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-white/60 print:text-gray-600">{detail.assessment.suggestions.map((suggestion) => <li key={suggestion}>{suggestion}</li>)}</ul><p className="mt-5 text-xs text-white/35 print:text-gray-500">Generated by {detail.assessment.model} · Screening guidance, not diagnosis.</p></div>}</section></> : <p className="future-panel mt-6 p-8 text-white/45">No final measurement stored for this session.</p>}
    {error && <p role="alert" className="mt-5 text-sm text-red-300 print:hidden">{error}</p>}
    <footer className="mt-10 border-t border-white/10 pt-5 text-xs text-white/35 print:border-gray-300 print:text-gray-500">Generated locally by HemoSync. Screening values require qualified clinical interpretation and do not replace diagnosis.</footer>
  </div></main>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="future-panel p-5 print:border-gray-300 print:bg-white print:shadow-none"><p className="text-xs uppercase tracking-[.15em] text-white/35 print:text-gray-500">{label}</p><p className="mt-2 break-words capitalize">{value}</p></div>; }
function Vital({ label, value, range }: { label: string; value: string; range: string }) { return <article className="future-panel p-7 print:border-gray-300 print:bg-white print:shadow-none"><p className="signal-label print:text-red-700">{label}</p><p className="mt-5 text-5xl font-semibold">{value}</p><p className="mt-4 text-sm text-white/40 print:text-gray-600">Observed range: {range}</p></article>; }
